#!/usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path('./lib', __FILE__)
require './lib/shipping-quote'

cart_items = []
class StubItem
  def shipCode; 'UPS';   end
  def isGlass; 1;  end
  def qty;  1;  end
  def weight; 20;  end
  def backorder; 0;  end
  def vendor; 10;  end
  def ormd; nil; end
  def glassConverter; nil; end
end
class StubCustomer
  def street; '1234 Fake Street'; end
  def street2; nil end
  def country; 'US'; end
  def city; 'Tampa'; end
  def state; 'FL' end
  def zip; '33609'; end
end
item = StubItem.new #{ shipCode: 'UPS', isGlass: nil, qty: 1, weight: 1, backorder: 0, vendor: 10 }
c = StubCustomer.new
cart_items[0] = item
cart_items[1] = item
cart_items[2] = item
config = YAML::load(IO.read("./shipping-quote-spec.yml"))
destination = { :country => 'US', :province => 'FL', :city => 'Tampa', :postal_code => '48910'}

config[:add_boxing_charge] = true
ship = ShippingQuote::Shipping.new(cart_items, config)
packages = ship.create_packages
boxing = ship.boxing_charge
binding.pry
#quote = ship.quotes(destination,packages)
#has_express = quote.select{|key, value| key.to_s.match(/^FedEx Express Saver/)}




#quotes = ship.quotes(destination,packages)
#truck_only = ship.truck_only
#puts truck_only
#packages = ship.create_packages
#quotes = ship.quotes(destination,packages)
#puts results = ship.filter_shipping(quotes, nil, nil, truck_only)
